######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 26 13:18:16 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
