######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 15 21:22:02 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
