######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 20 22:22:15 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += HelloQuit.cpp
