######################################################################
# Automatically generated by qmake (1.07a) Fri Sep 3 19:17:20 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += myserver.h
SOURCES += main.cpp myserver.cpp
