######################################################################
# Automatically generated by qmake (1.07a) Sat Sep 4 18:40:09 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += myserver.h
SOURCES += main.cpp myserver.cpp
