######################################################################
# Automatically generated by qmake (1.07a) Sat Sep 4 16:20:03 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += mymenu.h mymenu.ui.h
SOURCES += main.cpp mymenu.cpp
