######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 22 23:06:46 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += StandardDialogs.h
SOURCES += main.cpp StandardDialogs.cpp
