######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 26 17:20:45 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
