######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 11 13:38:05 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Helloworld.cc
