######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 29 10:18:07 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += WindowBox.cc
